### ISSUE TITLE
Improve managing global configuration

### ISSUE THREAD

**Issue by aniketnk** [pes-alcoding-club/posterior#8]
**Is your feature request related to a problem? Please describe.**
Let's have a better way to manage configuration. See [Best-Practices Config Guide].(https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/configguide.md)

Issue:
Error not informative
> error TS2307: Cannot find module './config' or its corresponding type declarations.

**Describe the solution you'd like**
Use some library like rc, nconf, config

**Describe alternatives you've considered**
Mentioned above

**Additional context**
None

**Comment by aniketnk** [comment]
I added the config.ts file, but now I'm getting another error
```sh
posterior/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/app.ts:6:20 - error TS2306: File '/Users/ani/work/posterior/src/config.ts' is not a module.

6 import config from './config';
                     ~~~~~~~~~~

    at createTSError (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

This error is different from the one described in the issue. 

How to reproduce: 
- Checkout Sparsh's fork, master branch at commit 5a5d6402b71faa44430088f58441186628975453
- Environment: MacOS, node v14.5.0

@temanisparsh need an urgent fix for this

**Comment by temanisparsh** [comment]
> I added the config.ts file, but now I'm getting another error
> 
> ```shell
> posterior/node_modules/ts-node/src/index.ts:434
>     return new TSError(diagnosticText, diagnosticCodes)
>            ^
> TSError: ⨯ Unable to compile TypeScript:
> src/app.ts:6:20 - error TS2306: File '/Users/ani/work/posterior/src/config.ts' is not a module.
> 
> 6 import config from './config';
>                      ~~~~~~~~~~
> 
>     at createTSError (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:434:12)
>     at reportTSError (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:438:19)
>     at getOutput (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:578:36)
>     at Object.compile (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:775:32)
>     at Module.m._compile (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:858:43)
>     at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
>     at Object.require.extensions.<computed> [as .ts] (/Users/ani/work/posterior/node_modules/ts-node/src/index.ts:861:12)
>     at Module.load (internal/modules/cjs/loader.js:1050:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:938:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
> ```
> 
> This error is different from the one described in the issue.
> 
> How to reproduce:
> 
> * Checkout Sparsh's fork, master branch at commit [5a5d640](https://github.com/pes-alcoding-club/posterior/commit/5a5d6402b71faa44430088f58441186628975453)
> * Environment: MacOS, node v14.5.0
> 
> @temanisparsh need an urgent fix for this

Have updated the config file to fix this

**Comment by temanisparsh** [comment]
We can use [config](https://www.npmjs.com/package/config) for this.
[nconf](https://www.npmjs.com/package/nconf) seems a bit too much.

**Comment by aniketnk** [comment]
Alright. Let's get that in another PR. Link it here.
